
export enum EmotionType {
  NEUTRAL = 'NEUTRAL',

  LIKE = 'LIKE',
  LOVE = 'LOVE',
  INSPIRED = 'INSPIRED',
  AMUSED = 'AMUSED',
  RELAXED = 'RELAXED',

  DISLIKE = 'DISLIKE',
  DISAPPOINTED = 'DISAPPOINTED',
  SAD = 'SAD',
  UNCOMFORTABLE = 'UNCOMFORTABLE',
  HATE = 'HATE',
}
